[package]
name = "dont-publish/prototype"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.4.3"
Kache = "synthetic-dev/kache@^1.0.1"
Component = "sleitnick/component@^2.4.3"

[place]
shared-packages = "game.ReplicatedStorage.Packages"